django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('profile/update/', user_views.update_profile, name='profile-update'),
    path('token-check/', user_views.token_check_view, name='token-check'),
    path('', include('gallery_app.urls')),
]

gallery_app/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', home, name='home'),

    path('photos/', photos, name='photos'),
    path('photos/create/', PhotoCreateView.as_view(), name='photo-create'),
    path('photos/<int:pk>/', PhotoDetailView.as_view(), name='photo-details'),
    path('photos/<int:pk>/edit/', PhotoEditView.as_view(), name='photo-edit'),
    path('photos/<int:pk>/delete/', PhotoDeleteView.as_view(), name='photo-delete'),

    path('videos/', videos, name='videos'),
    path('videos/create/', VideoCreateView.as_view(), name='videos-create'),
    path('videos/<int:pk>/', VideoDetailView.as_view(), name='video-details'),
    path('videos/<int:pk>/edit/', VideoEditView.as_view(), name='videos-edit'),
    path('videos/<int:pk>/delete/', VideoDeleteView.as_view(), name='videos-delete'),

    path('voices/', voices, name='voices'),
    path('voices/create/', VoiceCreateView.as_view(), name='voices-create'),
    path('voices/<int:pk>/', VoiceDetailView.as_view(), name='voice-details'),
    path('voices/<int:pk>/edit/', VoiceEditView.as_view(), name='voices-edit'),
    path('voices/<int:pk>/delete/', VoiceDeleteView.as_view(), name='voices-delete'),

    path('chats/', chats, name='chats'),
    path('chats/create/', ChatCreateView.as_view(), name='chats-create'),
    path('chats/<int:pk>/', ChatDetailView.as_view(), name='chat-details'),
    path('chats/<int:pk>/edit/', ChatEditView.as_view(), name='chats-edit'),
    path('chats/<int:pk>/delete/', ChatDeleteView.as_view(), name='chats-delete'),

    path('post-type/', select_post_type, name='select-post-type')
]

gallery_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PostCard(models.Model):
    class Meta:
        abstract = True

    title = models.CharField(max_length=100, blank=True)
    body = models.TextField(blank=True, null=True)
    image = models.URLField()
    date = models.DateField(default=timezone.now)
    modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def default_title(self):
        try:
            default_title = f"post-{PostCard.objects.last().id + 1}"
        except AttributeError:
            default_title = f"post-1"

        return default_title

    def save(self, *args, **kwargs):
        if not self.pk and not self.title:
            self.title = self.default_title()
        super().save(*args, **kwargs)

    view_name = 'view_name'

    def get_absolute_url(self):
        return reverse(viewname=self.view_name, kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class PhotoCard(PostCard):
    def default_title(self):
        try:
            default_title = f"photo-{PhotoCard.objects.last().id + 1}"
        except AttributeError:
            default_title = f"photo-1"

        return default_title

    view_name = 'photo-details'


class VideoCard(PostCard):
    def default_title(self):
        try:
            default_title = f"video-{VideoCard.objects.last().id + 1}"
        except AttributeError:
            default_title = f"video-1"

        return default_title

    view_name = 'video-details'


class VoiceCard(PostCard):
    def default_title(self):
        try:
            default_title = f"voice-{VoiceCard.objects.last().id + 1}"
        except AttributeError:
            default_title = f"voice-1"

        return default_title

    view_name = 'voice-details'


class ChatCard(PostCard):
    def default_title(self):
        try:
            default_title = f"chat-{ChatCard.objects.last().id + 1}"
        except AttributeError:
            default_title = f"chat-1"

        return default_title

    view_name = 'chat-details'

gallery_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from .models import PhotoCard, VideoCard, VoiceCard, ChatCard
from users.models import Token
from django.db.models import Q
from django.core.paginator import Paginator


@login_required
def home(request):
    return render(request, 'gallery_app/home_page.html')


def views_abstract(request, view_page, model):

    search_query = request.GET.get('q', '')
    sort_order = request.GET.get('sort', '')
    order_by = request.GET.get('order-by', '?')

    if sort_order == 'DES':
        DES_icon = "fa-solid fa-arrow-down-z-a"
        ASC_DES_icon = DES_icon
        ASC_DES = 'ASC'
    else:
        ASC_icon = "fa-solid fa-arrow-up-a-z"
        ASC_DES_icon = ASC_icon
        ASC_DES = 'DES'

    sorting_url = f"{reverse(view_page)}?q={search_query}&order-by={order_by}"
    ordering_url = f"{reverse(view_page)}?q={search_query}&sort={sort_order}"
    pagination_url = f"{reverse(view_page)}?q={search_query}&sort={sort_order}&order-by={order_by}"

    posts_list = model.objects.filter(
        Q(title__icontains=search_query) |
        Q(body__icontains=search_query) |
        Q(date__icontains=search_query) |
        Q(author__username__icontains=search_query)
    ).order_by('-' + order_by if sort_order == 'DES' and order_by != '?' else order_by)

    content_count = posts_list.count()

    paginator = Paginator(posts_list, 20)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    objs_num = len(page_obj)
    col_objs_num = objs_num // 4
    rem_division = objs_num % 4
    col_01_rem = 0
    col_02_rem = 0
    col_03_rem = 0
    if rem_division == 3:
        col_01_rem = 1
        col_02_rem = 2
        col_03_rem = 3
    if rem_division == 2:
        col_01_rem = 1
        col_02_rem = 2
        col_03_rem = 2
    if rem_division == 1:
        col_01_rem = 1
        col_02_rem = 1
        col_03_rem = 1

    col_01_objs = page_obj[:col_objs_num+col_01_rem]
    col_02_objs = page_obj[col_objs_num+col_01_rem:col_objs_num*2+col_02_rem]
    col_03_objs = page_obj[col_objs_num*2+col_02_rem:col_objs_num*3+col_03_rem]
    col_04_objs = page_obj[col_objs_num*3+col_03_rem:]
    cols_objs = [col_01_objs, col_02_objs, col_03_objs, col_04_objs]

    return {
        'view_page': view_page,
        'cols_objs': cols_objs,

        'ASC_DES': ASC_DES,
        'ASC_DES_icon': ASC_DES_icon,

        'sorting_url': sorting_url,
        'ordering_url': ordering_url,
        'pagination_url': pagination_url,

        'content_count': content_count,
        'page_obj': page_obj,
    }


@login_required
def photos(request):
    context = views_abstract(request, 'photos', PhotoCard)
    return render(request, 'gallery_app/posts_pages/photos_page.html', context)


@login_required
def videos(request):
    context = views_abstract(request, 'videos', VideoCard)
    return render(request, 'gallery_app/posts_pages/videos_page.html', context)


@login_required
def voices(request):
    context = views_abstract(request, 'voices', VoiceCard)
    return render(request, 'gallery_app/posts_pages/voices_page.html', context)


@login_required
def chats(request):
    context = views_abstract(request, 'chats', ChatCard)
    return render(request, 'gallery_app/posts_pages/chats_page.html', context)


class AbstractCreateView(LoginRequiredMixin, CreateView):
    fields = ['title', 'body']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        token_obj = Token.objects.get(user=self.request.user)
        context['access_token'] = token_obj.access_token
        return context

    def form_valid(self, form):
        form.instance.image = self.request.POST.get('image')
        if self.request.POST.get('date'):
            form.instance.date = self.request.POST.get('date')
        form.instance.author = self.request.user
        return super().form_valid(form)


class PhotoCreateView(AbstractCreateView):
    model = PhotoCard
    template_name = 'gallery_app/create&edit_pages/photo_create.html'


class VideoCreateView(AbstractCreateView):
    model = VideoCard
    template_name = 'gallery_app/create&edit_pages/video_create.html'


class VoiceCreateView(AbstractCreateView):
    model = VoiceCard
    template_name = 'gallery_app/create&edit_pages/video_create.html'


class ChatCreateView(AbstractCreateView):
    model = ChatCard
    template_name = 'gallery_app/create&edit_pages/photo_create.html'


def select_post_type(request):
    return render(request, 'gallery_app/create&edit_pages/select_post_type.html')


class AbstractDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    template_name = 'gallery_app/post_details.html'
    fields = ['title', 'body', 'image', 'date']

    def test_func(self):
        photo_card = self.get_object()
        if self.request.user == photo_card.author:
            return True
        return False


class PhotoDetailView(AbstractDetailView):
    model = PhotoCard


class VideoDetailView(AbstractDetailView):
    model = VideoCard


class VoiceDetailView(AbstractDetailView):
    model = VoiceCard


class ChatDetailView(AbstractDetailView):
    model = ChatCard


class AbstractEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    fields = ['title', 'body']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        token_obj = Token.objects.get(user=self.request.user)
        context['access_token'] = token_obj.access_token
        return context

    def form_valid(self, form):
        form.instance.image = self.request.POST.get('image')
        if self.request.POST.get('date'):
            form.instance.date = self.request.POST.get('date')
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        photo_card = self.get_object()
        if self.request.user == photo_card.author:
            return True
        return False


class PhotoEditView(AbstractEditView):
    model = PhotoCard
    template_name = 'gallery_app/create&edit_pages/photo_create.html'


class VideoEditView(AbstractEditView):
    model = VideoCard
    template_name = 'gallery_app/create&edit_pages/video_create.html'


class VoiceEditView(AbstractEditView):
    model = VoiceCard
    template_name = 'gallery_app/create&edit_pages/video_create.html'


class ChatEditView(AbstractEditView):
    model = ChatCard
    template_name = 'gallery_app/create&edit_pages/photo_create.html'


class AbstractDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'gallery_app/post_delete.html'
    success_url = '/profile/'

    def test_func(self):
        photo_card = self.get_object()
        if self.request.user == photo_card.author:
            return True
        return False


class PhotoDeleteView(AbstractDeleteView):
    model = PhotoCard


class VideoDeleteView(AbstractDeleteView):
    model = VideoCard


class VoiceDeleteView(AbstractDeleteView):
    model = VoiceCard


class ChatDeleteView(AbstractDeleteView):
    model = ChatCard

gallery_app/templates/gallery_app/create&edit_pages/photo_create.html
{% extends "gallery_app/create&edit_pages/post_create_base.html" %}

{% block uploaded_post %}
    <img class="uploaded-image" src="{{ object.image }}">
{% endblock %}


{% block file_input %}
    <input type="file" accept="image/jpeg,image/png,image/gif" id="file-input" hidden>
{% endblock %}


{% block api_headers %}

    <script>
        //  API Headers
        const postType = "image"
        const accessToken = "{{ access_token }}"
        {% if request.path == "/photos/create/" %}
            const album = "iDZwfLO"
        {% else %}
            const album = "iDZwfLO"
        {% endif %}
        const file_type = "image"
    </script>

{% endblock %}

gallery_app/templates/gallery_app/create&edit_pages/post_create_base.html
{% extends "gallery_app/base.html" %}
{% load static %}
{% block heads %}
    <link rel="stylesheet" href="{% static 'post_create_style.css' %}">
    <title>Create Post</title>
{% endblock heads %}


{% block header %}
    {% include "widgets/profile_header.html" %}
{% endblock header %}


{% block content %}

    <form method="POST" class="form-box">
        {% csrf_token %}

        <div class="text-form">

            <h1>Create New Post</h1>

            {{ form.as_div }}

            <button class="create-btn" id="pc" type="submit">Create</button>

        </div>

        <div class="image-form">

            <input type="text" maxlength="100" value="{{ object.image }}" required name="image" id="id_image" hidden>

            <button class="upload-btn" type="button">

                {% block uploaded_post %}{% endblock %}

                <div class="upload-icon">
                    <i class="fa-solid fa-icons"></i>
                    <span>Choose Photo/Video</span>
                </div>

                <div class="spinner" style="display: none;">
                    {% include "widgets/spinner.html" %}
                </div>

            </button>

            <div class="date-input">
                <label for="id_date">Image date:</label>
                <input type="date" maxlength="10" value="{{ object.date|date:'Y-m-d' }}" name="date" id="id_date">
                <i class="fa-regular fa-calendar-days" id="calendar-icon"></i>
            </div>

        </div>

        <button class="create-btn" id="phone" type="submit">Create</button>

    </form>

    {% block file_input %}{% endblock %}

    <style>

        .ripples {
            position: absolute;
            background: #646464;
            transform: translate(-50%, -50%);
            pointer-events: none;
            border-radius: 50%;
            box-shadow: 0 0 10px rgba(0, 0, 0, .1);
            animation: drop .5s linear;
        }
    
        @keyframes drop {
    
            0% {
                width: 0;
                height: 0;
                opacity: 0.5;
            }
            100% {
                width: 1000px;
                height: 1000px;
                opacity: 0;
            }
        }
    
    </style>

    <script>

        var buttons = document.querySelectorAll(".create-btn")

        buttons.forEach(element => {
            element.addEventListener("click", function(e) {
                let x = e.clientX - element.getBoundingClientRect().left
                let y = e.clientY - element.getBoundingClientRect().top

                let ripples = document.createElement("span")
                ripples.className = "ripples"
                ripples.style.left = x + "px"
                ripples.style.top = y + "px"
                this.appendChild(ripples)

                setTimeout(() => {
                    ripples.remove()
                }, 1000)
            })
        })

    </script>

    {% block api_headers %}{% endblock %}

    <script src="{% static 'upload_api.js' %}"></script>

{% endblock content %}

gallery_app/templates/gallery_app/create&edit_pages/select_post_type.html
{% extends "gallery_app/base.html" %}
{% load static %}
{% block heads %}
    <link rel="stylesheet" href="{% static 'post_type_style.css' %}">
    <title>Post Type</title>
{% endblock heads %}


{% block header %}
    {% include "widgets/profile_header.html" %}
{% endblock header %}


{% block content %}

    <h2 class="title">Choose post type!</h2>

    <div class="container">

        <a class="card" href="{% url 'photo-create' %}">
            <i class="fa-solid fa-images"></i>
            <h2>Photo</h2>
        </a>

        <a class="card" href="{% url 'videos-create' %}">
            <i class="fa-solid fa-photo-film"></i>
            <h2>Video</h2>
        </a>

        <a class="card" href="{% url 'voices-create' %}">
            <i class="fa-solid fa-microphone"></i>
            <h2>Voice</h2>
        </a>

        <a class="card" href="{% url 'chats-create' %}">
            <i class="fa-sharp fa-solid fa-comments"></i>
            <h2>Chat</h2>
        </a>

    </div>

{% endblock content %}

gallery_app/templates/gallery_app/create&edit_pages/video_create.html
{% extends "gallery_app/create&edit_pages/post_create_base.html" %}

{% block uploaded_post %}
    {% if object.image %}
        <video preload="metadata" controls>
            <source class="uploaded-image" type="video/mp4" src="{{ object.image }}">
        </video>
    {% else %}
        <video>
            <source class="uploaded-image" type="video/mp4" src="">
        </video>
    {% endif %}
{% endblock %}


{% block file_input %}
    <input type="file" accept="video/mp4" id="file-input" hidden>
{% endblock %}


{% block api_headers %}

    <script>
        //  API Headers
        const postType = "upload"
        const accessToken = "{{ access_token }}"
        {% if request.path == "/videos/create/" %}
            const album = "iDZwfLO"
        {% else %}
            const album = "iDZwfLO"
        {% endif %}
        const file_type = "video"
    </script>

{% endblock %}